### ISSUE TITLE
Getting an empty gzipped phrase table

### ISSUE THREAD

**Issue by gvskalyan** [OpenNMT/papers#1]
Hi @jsenellart @srush , 
what should be the N value passed to docker while creating phrase table, not passing it and passing a huge value such as 128 (assuming phrase contains 10 words with around 10 characters) outputs an empty file after around 40 + minutes on a 16 core machine.

Input : train files containing sentencepiece-tokenized sentences.

while processing  : 
![image](https://user-images.githubusercontent.com/42022935/77162386-dc014000-6ad1-11ea-9128-b7debb71ef1e.png)

Ref : https://github.com/OpenNMT/papers/tree/master/WNMT2018/vmap#building-phrase-table

**Comment by guillaumekln** [comment]
For reference, this was discussed on the forum: https://forum.opennmt.net/t/get-vmap-from-the-corpus-to-be-used-in-ctranslate2/3573

There were some issues with the training data (mostly empty lines). This is fixed by https://github.com/OpenNMT/papers/commit/c44b9ffdb561da7e963f835cb90aa5f56e20c6f4 which adds a basic filtering.
